updates

diff --git a/.github/workflows/github-action.yaml b/.github/workflows/github-action.yaml
--- a/.github/workflows/github-action.yaml
+++ b/.github/workflows/github-action.yaml
@@ -28,7 +28,7 @@ jobs:
   docker_build_and_push:
     name: Docker build and push
     needs: lint
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04-arm
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -65,10 +65,11 @@ jobs:
           tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
           build-args: |
             "NEXT_PUBLIC_ENV=${{ env.NEXT_PUBLIC_ENV }}"
-            "POPO_VERSION=${{ if(eq(env.NEXT_PUBLIC_ENV, 'prod'), github.ref_name, github.sha) }}"
+            "POPO_VERSION=${{ github.event.release.tag_name || github.sha }}"
           cache-from: type=gha
           cache-to: type=gha,mode=max
           push: true
+          provenance: false # Disable image index metadata
 
   redeploy_dev_service:
     name: Redeploy Dev Service
@@ -76,7 +77,14 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Redeploy Dev Service
-        run: curl -X POST ${{ secrets.PORTAINER_DEV_SERVICE_WEBHOOK }}
+        run: |
+          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST ${{ secrets.PORTAINER_DEV_SERVICE_WEBHOOK }})
+          if [ "$RESPONSE" -ne 204 ]; then
+            echo "❌ Deployment failed! HTTP Response: $RESPONSE"
+            cat response.txt  # 오류 메시지 출력 (필요 시)
+            exit 1
+          fi
+          echo "✅ Deployment successful! HTTP Response: $RESPONSE"
 
   deploy_health_check:
     name: Check Application Status
